server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # 1. JUGADOR SERVICE 
            - id: jugador-service
              uri: lb://jugador-service 
              predicates:
                - Path=/api/jugadores/**, /api/mazos/**

            # 2. TORNEO SERVICE 
            - id: torneo-service
              uri: lb://torneo-service 
              predicates:
                - Path=/api/torneos/**

            # 3. RECINTO SERVICE 
            - id: recinto-service
              uri: lb://recinto-service 
              predicates:
                - Path=/api/recintos/**


# Swagger-UI 
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: 1. API Jugadores y Mazos (jugador-service)
        url: /api/jugadores/v3/api-docs
      - name: 2. API Motor de Torneos (torneo-service)
        url: /api/torneos/v3/api-docs
      - name: 3. API Recintos y Locaciones (recinto-service)
        url: /api/recintos/v3/api-docs
  api-docs:
    enabled: true
